# Generated by Django 4.2.9 on 2024-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_preview',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
